- name: variable with files
  hosts: web
  vars_files:
  - var.yaml
  tasks:
  - name: print the info
    anisble.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, duration of course is {{DURATION}} and the Trainer name is {{TRAINER}}"