- name: vars with prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the prompt
  - name: TRAINER
    prompt: please enter the prompt
  - name: DURATION
    prompt: please enter the prompt
  tasks:
    - name: print the info
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, duration of course is {{DURATION}} and the Trainer name is {{TRAINER}}"
    