- name: variable with datatypes
  hosts: web
  vars: 
    COURSE: "DEVOPS WITH AWS" #string
    DURATION: 120 HOURS #number
    topics: #list
    - GIT 
    - GITHUB
    - ANSIBLE
    - TERRAFORM
    - JENKINS
    - DOCKER
    - K8s
    - AWS
    live: true #boolean  
    tools: #map/dictinary
      ci: jenkins
      cm: ansible
      cloud: aws
      aws:
      - IAM
      - S3 BUCKET
      - R53 ROUTE
  tasks: 
  - name: "devops with aws"
    anisble.builtin.debug:
      msg: "Hi, i am learning {{COURSE}}, duration is {{DURATION}}. We do have topics like {{topics}} and I course is {{live}}. Here learn 
      tools like {{tools}}" 


    