- name: checking given number is greater than 10 or not 
  hosts: local
  connection: local
  vars_prompt: 
  - name: my_nummber
    prompt: please enter the number
    private: false
  tasks: 
  - name: my_number
    anisble_builtin_debugd:
    msg: "Given number {{my_number}} is less that 10"
    when: my_number | int < 10
  - name: my_number
    anisble_builtin_debugd:
    msg: "Given number {{my_number}} is greater that 10"
    when: my_number | int >= 10    