- name: 
  hosts: web
  become: yes
  tasks: 
  - name: create user exits or not
    anisble_builtin_command: id expense
    register: USER # here USER is a variable that gets output from above command
    ignore_errors: true

  - name: print user information
    anisble_builtin_debug:
     msg: "user info: {{ USER}}"  

  - name: create user exits or not
    anisble_builtin_command: useradd expense
    register: USER # here USER is a variable that gets output from above command
    
   