- name: create user
  hosts: web
  become: yes
  tasks: 
  - name: create user exits or not
    anisble.builtin.command: id expense
    register: USER # here USER is a variable that gets output from above command
    ignore_errors: True

  - name: print user information
    anisble.builtin.debug:
     msg: "user info: {{ USER}}"  

  - name: create user exits or not
    anisble.builtin.command: useradd expense
    register: USER # here USER is a variable that gets output from above command
    
   