- name: nginx
  hosts: local
  become: yes
  tasks:
  - name: Print the stats
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: Install nginx if RedHat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install nginx if Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"



# - name: install nginx
#   become: yes
#   hosts: web
#   tasks:
#   - name: print the stats
#     ansible.builtin.debug:
#       msg: "{{ ansible_facts }}"
  
#   - name: install nginx if redhat
#     ansible.builtin.dnf:
#       name: nginx
#       state: present
#     when: ansible_os_family == "RedHat"

#   - name: install nginx if Debian
#     ansible.builtin.apt:
#       name: nginx
#       state: present
#     when: ansible_os_family == "Debian"
