- name: loop demo
  connection: local
  hosts: local
  tasks:
  - name: print the list of names
    ansible.builtin.debug:
      msg: " Hello {{ item }} "
    loops:
    - Ramesh
    - suresh
    - umesh
    - Rakesh  