- name: loops demo
  connection: local
  hosts: local
  tasks:
  - name: print the list of names
    ansible.builtin.debug:
      msg: "Hello {{ item }} "
    loop:
    - Ramesh
    - suresh
    - umesh
    - Rakesh  