- name: loops demo
  become: yes
  hosts: web
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - git
    - httpd
    - maven

  - name: status enabled
    ansible.builtin.service:
      name: "{{ item }}"
      state: present
      enabled: yes
    loop:
    - mysql
    - nginx
    - git
    - httpd