- name: loops demo
  become: yes
  hosts: web
  tasks:
  - name: print the list of names
    ansible.builtin.package:
      msg: "Hello {{ item }}"
    loop:
    - mysql
    - nginx
    - git
    - httpd