- name: demo on filter
  hosts: local
  connection: local
  tasks: 
  - name: print the default variable 
    ansible.builtin.debug:
     msg: "hello, {{ course | default('Ansible') }}"

  - name: print in uppercase 
    vars: 
       greetings: "hello, ramesh"
    ansible.builtin.debug:
     msg: "{{ greetings | upper }}"    

  
  - name: print in lowercase
    vars: 
       greetings: "HELLO, SURESH"
    ansible.builtin.debug:
     msg: "{{ greetings | lower }}"

  - name: print in unique numbers
    vars: 
       number: [1, 4, 6, 9, 9, 49, 1 , 1 ,25, 45, 59,] 
    ansible.builtin.debug:
     msg: "{{ number | unique }}"          

  - name: print in minimum and maximum numbers
    vars: 
       number: [1, 4, 6, 9, 456, 25, 226, 45, 59, 88, 101,] 
    ansible.builtin.debug:
     msg: "min {{ number | min }} , max {{ number | max }}"    

  - name: convert map to list
    vars:
     course: 
      name: "Devops with aws"
      duration: 120
      trainer: "sivakumar reddy"
    ansible.builtin.debug:
     msg: " {{ course | dict2items }}"     

  - name: convert list to map
    vars:
     course: 
     - {'key': 'name', 'value': 'Devops with aws'}
     - {'key': 'duration', 'value': 120}
     - {'key': 'trainer', 'value': 'sivakumar reddy'}
    ansible.builtin.debug:
     msg: " {{ course | items2dict }}"   

  - name: check ip address
    vars:
     myip: "198.162.1.1"
    ansible.builtin.debug:
     msg: " {{ myip | ansible.utils.ipv4 }} "     








          