- name: demo on filter
  hosts: local
  connection: local
  tasks: 
  - name: print the default variable 
    ansible.builtin.debug:
      msg: "hello, {{ course | default('Ansible') }}"

  - name: print in uppercase 
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"    