- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
   subnet_id: "subnet-0b49346919c8a4222 "
   sg_id: " sg-0ba969f3e22a48b24 "
   ami_id: " ami-09c813fb71547fc4f "    
   instances:
    - mysql
    - backend
    - frontend
   zone: learningdevops.shop
  tasks:   
  - name: create ec2 instance
    amazon.aws.ec2.instance:
    vpc_subnet_id: "{{ subnet_id }}"
    instance_type: t2.micro
    security_group: "{{ sq_id }}"
    image_id: "{{  ami_id }}"
    loop: "{{ instances}}"
      
