- name: sshd install and run
  hosts: web
  become: yes #take sudo access
  tasks:
  - name: install sshd
    ansible.builtin.package: #heterongenous module that can work for all distros
      name: sshd
      state: present
  
  - name: run sshd
    ansible.builtin.service:
      name: sshd
      state: started
      enabled: yes