- name: mysql-server install and run
  hosts: web
  become: yes #take sudo access
  tasks:
  - name: install mysql-server
    ansible.builtin.package: #heterongenous module that can work for all distros
      name: mysql-server
      state: present
  
  - name: mysqld
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes