- name: ssh install and run
  hosts: web
  become: yes #take sudo access
  tasks:
  - name: install ssh
    ansible.builtin.package: #heterongenous module that can work for all distros
      name: ssh
      state: present
  
  - name: run ssh
    ansible.builtin.service:
      name: ssh
      state: started
      enabled: yes