- name: httpd
  hosts: web
  become: yes
  tasks: #install httpd
  - name: httpd
    ansible.builtin.package:
     name: mysql
     state: present

  - name: run httpd
    ansible.builtin.service:
     name: httpd
     state: started
     enabled: yes