- name: httpd install and run
  hosts: web
  become: yes #take sudo access
  tasks:
  - name: install httpd
    ansible.builtin.package: #heterongenous module that can work for all distros
      name: httpd
      state: present
  
  - name: run httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes