- name: mysqld
  hosts: web
  become: yes
  tasks: #install mysqld
  - name: mysqld
    ansible.builtin.package:
     name: mysql
     state: present

  - name: run mysqld
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes