- name: mysql
  hosts: web
  become: yes
  tasks: #install mysql
   - name: mysql
     ansible.builtin.package:
      name: mysql
      state: present

   - name: mysql status
     ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes