- name: git
  hosts: web
  become: yes
  tasks: #install git
  - name: git
    ansible.builtin.package:
     name: mysql
     state: present

  - name: run git
    ansible.builtin.service:
     name: git
     state: started
     enabled: yes