- name: openssh-server install and run
  hosts: web
  become: yes #take sudo access
  tasks:
  - name: install openssh-server
    ansible.builtin.package: #heterongenous module that can work for all distros
      name: openssh-server
      state: present
  
  - name: ssh.service
    ansible.builtin.service:
      name: openssh-server
      state: started
      enabled: yes