- name: Ngnix
  hosts: web
  become: yes
  tasks: #install nginx
    - name: nginx
      ansible.builtin.package:
        state: present

    - name: nginx status
      ansible.builtin.service:
        state: started
        enabled: yes