- name: mysql
  hosts: web
  become: yes
  tasks: #install mysql
   - name: mysql
     ansible.builtin.package:
      state: mysql

   - name: mysql status
     ansible.builtin.service:
      state: started
      enabled: yes